package com.person.ua.dao.entity;

import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableName;
import lombok.Data;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * 'test_order_db.sw_report' is not BASE TABLE
 * @TableName t_order_payment
 */
@TableName(value ="t_order_payment")
@Data
public class TOrderPayment implements Serializable {
    /**
     * Tenant code
     */
    @TableField(value = "TENANT_CODE")
    private String tenantCode;

    /**
     * Domain code
     */
    @TableField(value = "DOMAIN_CODE")
    private String domainCode;

    /**
     * Org code
     */
    @TableField(value = "ORG_CODE")
    private String orgCode;

    /**
     * Channel code
     */
    @TableField(value = "CHANNEL_CODE")
    private String channelCode;

    /**
     * Order code
     */
    @TableField(value = "ORDER_CODE")
    private String orderCode;

    /**
     * External order code
     */
    @TableField(value = "EXTERNAL_ORDER_CODE")
    private String externalOrderCode;

    /**
     * Pay serial code
     */
    @TableField(value = "PAY_SERIAL_CODE")
    private String paySerialCode;

    /**
     * Pay code , generated by financial module
     */
    @TableField(value = "PAY_CODE")
    private String payCode;

    /**
     * Pay ment type online,offline
     */
    @TableField(value = "PAY_MENT_TYPE")
    private String payMentType;

    /**
     * Pay ment
     */
    @TableField(value = "PAY_MENT")
    private String payMent;

    /**
     * Pay channel
     */
    @TableField(value = "PAY_CHANNEL")
    private String payChannel;

    /**
     * Currency code
     */
    @TableField(value = "CURRENCY_CODE")
    private String currencyCode;

    /**
     * Pay ext props
     */
    @TableField(value = "PAY_EXT_PROPS")
    private String payExtProps;

    /**
     * Pay account
     */
    @TableField(value = "ACCOUNT")
    private String account;

    /**
     * Bank code
     */
    @TableField(value = "BANK_CODE")
    private String bankCode;

    /**
     * Bank brand
     */
    @TableField(value = "BANK_BRAND")
    private String bankBrand;

    /**
     * Price
     */
    @TableField(value = "PRICE")
    private BigDecimal price;

    /**
     * Pay is Success: 1 Yes,0 No
     */
    @TableField(value = "IS_SUCCEED")
    private String isSucceed;

    /**
     * Card No
     */
    @TableField(value = "CARD_NO")
    private String cardNo;

    /**
     * Pay failed reason
     */
    @TableField(value = "REASON")
    private String reason;

    /**
     * Create time
     */
    @TableField(value = "CREATE_TIME")
    private Date createTime;

    /**
     * Update time
     */
    @TableField(value = "UPDATE_TIME")
    private Date updateTime;

    /**
     * Delete time
     */
    @TableField(value = "DELETE_TIME")
    private Date deleteTime;

    /**
     * Create user name
     */
    @TableField(value = "CREATE_USER")
    private String createUser;

    /**
     * Update user name
     */
    @TableField(value = "UPDATE_USER")
    private String updateUser;

    /**
     * 
     */
    @TableField(value = "PAY_STATUS")
    private String payStatus;

    @TableField(exist = false)
    private static final long serialVersionUID = 1L;
}